RentFlat.Web/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentFlat.Model;
using Microsoft.AspNet.Identity;
using RentFlat.Web.Infrastructure.FileHelpers;

namespace RentFlat.Web.Controllers
{
    [Authorize]
    public class PicturesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Pictures
        public async Task<ActionResult> Index()
        {
            string userId = User.Identity.GetUserId();

            var pictures = db.Pictures.Include(p => p.Flat).Where( id => id.Flat.OwnerId == userId);
            return View(await pictures.ToListAsync());
        }

        // GET: Pictures/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = await db.Pictures.FindAsync(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // GET: Pictures/Create
        public ActionResult Create()
        {
            string userId = User.Identity.GetUserId();
            var flats = db.Flats.Where(id => id.OwnerId == userId).ToList();
            ViewBag.FlatId = new SelectList(flats, "ID", "FlatName");
            return View();
        }

        // POST: Pictures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Picture picture, HttpPostedFileBase upload)
        {
            string userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                if (upload.ContentLength > 0)
                {
                    string fileName = FileUtils.UploadFile(upload, User.Identity.GetUserName(), picture.FlatId.ToString());

                    if(fileName != null && fileName.Length > 0)
                    {
                        picture.LinkToImage = fileName;
                        db.Pictures.Add(picture);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                   
                }
                
            }

            var flats = db.Flats.Where(id => id.OwnerId == userId).ToList();
            ViewBag.FlatId = new SelectList(flats, "ID", "FlatName", picture.FlatId);
            ViewBag.UpLoadMessage = "Unable to Upload Picture";
            return View(picture);
        }

        // GET: Pictures/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = await db.Pictures.FindAsync(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            ViewBag.FlatId = new SelectList(db.Flats, "ID", "FlatName", picture.FlatId);
            return View(picture);
        }

        // POST: Pictures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Name,LinkToImage,FlatId")] Picture picture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(picture).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.FlatId = new SelectList(db.Flats, "ID", "FlatName", picture.FlatId);
            return View(picture);
        }

        // GET: Pictures/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = await db.Pictures.FindAsync(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // POST: Pictures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Picture picture = await db.Pictures.FindAsync(id);
            db.Pictures.Remove(picture);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PictureExists(int id)
        {
            return db.Pictures.Count(e => e.ID == id) > 0;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RentFlat.Web/Views/Pictures/Create.cshtml
@model RentFlat.Model.Picture

@{
    ViewBag.Title = "Link Picture with Flat";
}

<div class="row">
    <div class="top-bottom-padding">
        <h2>@ViewBag.Title</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Create", "Pictures", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Select File", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="upload" class="form-control" />
                        <span style="color:green">@ViewBag.UpLoadMessage</span>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.FlatId, "FlatId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("FlatId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.FlatId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="ADD" class="btn btn-warning" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-6">
       
    </div>
</div>


<div class="row">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RentFlat.Web/Views/Pictures/Delete.cshtml
@model RentFlat.Model.Picture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Flat.FlatName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flat.FlatName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LinkToImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LinkToImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RentFlat.Web/Views/Pictures/Details.cshtml
@model RentFlat.Model.Picture
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Details";
    var username = User.Identity.GetUserName();
    var imagePath = "~/Content/Uploads/" + username + "/" + Model.FlatId + "/" + Model.LinkToImage;
}

<div class="row">
    <h2>Image Details</h2>
    <hr />
</div>

<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Flat.FlatName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Flat.FlatName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>
    </div>
    <div class="col-md-6">
        <img src="@Url.Content(imagePath)" alt="image" class="img-responsive" />
    </div>
</div>
<div class="row">
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

RentFlat.Web/Views/Pictures/Edit.cshtml
@model RentFlat.Model.Picture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LinkToImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LinkToImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LinkToImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlatId, "FlatId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FlatId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FlatId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RentFlat.Web/Views/Pictures/Index.cshtml
@model IEnumerable<RentFlat.Model.Picture>

@{
    ViewBag.Title = "List of Flat Pictures";
}

<div class="row">
    <h2>
        @ViewBag.Title
        @Html.ActionLink("Add Image", "Create", null, new { @class = "btn btn-success pull-right" })
    </h2>
</div>

<div class="row">
    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Flat.FlatName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkToImage)
            </th>
            <th>ACTION</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Flat.FlatName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LinkToImage)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
</div>