RentFlat.Web/Models/ViewModels/RentViewModel.cs
using RentFlat.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RentFlat.Web.Models.ViewModels
{
    public class RentViewModel
    {
        [Display(Name = "Flat Name")]
        public string FlatName { get; set; }
        [Display(Name = "Flat Number")]
        public string FlatNumber { get; set; }
        [Display(Name = "Number of rooms")]
        public int RoomNumber { set; get; }
        public string Country { set; get; }
        public string City { get; set; }
        public string Address { set; get; }
        public string District { set; get; }
        public string Description { set; get; }
        [Display(Name = "Price for day")]
        public decimal PriceForDay { set; get; }
        [Display(Name = "Price for month")]
        public decimal PriceForMonth { set; get; }
        public double Latitude { set; get; }
        public double Longitude { set; get; }
        public int ZipCode { set; get; }

        public IEnumerable<Facility> Facilities { set; get; }
        public IEnumerable<Picture> Pictures { set; get; }
    }
}

RentFlat.Web/Controllers/HomeController.cs
using RentFlat.Model;
using RentFlat.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RentFlat.Web.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index(string keywords, string city)
        {
            ViewBag.keywords = keywords;
            ViewBag.city = city;
            
            if( string.IsNullOrEmpty(keywords) && string.IsNullOrEmpty(city))
            {
                return View();
            }

            var rents = this.db.Rents.Where( s => s.isRentAvaiable == true && s.Flat.Description.Contains(keywords) | keywords == null && s.Flat.City.ToUpper() == city.ToUpper() | city == null )
              .OrderBy(d => d.Flat.City)
              .ToList();

            return View(rents);
        }

        public async Task<ActionResult> Rents(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = await db.Rents.FindAsync(id);
            if (rent == null)
            {
                return HttpNotFound();
            }

            RentViewModel model = new RentViewModel();
            model.Address = rent.Flat.Address;
            model.City = rent.Flat.City;
            model.Country = rent.Flat.Country;
            model.Description = rent.Flat.Country;
            model.District = rent.Flat.District;
            model.FlatName = rent.Flat.FlatName;
            model.FlatNumber = rent.Flat.FlatNumber;
            model.RoomNumber = rent.Flat.RoomNumber;
            model.Latitude = rent.Flat.Latitude;
            model.Longitude = rent.Flat.Longitude;
            model.PriceForMonth = rent.Flat.PriceForMonth;
            model.PriceForDay = rent.Flat.PriceForDay;
            model.ZipCode = rent.Flat.ZipCode;

            model.Facilities = rent.Flat.Facilities.Select(i => i.Facility);
            model.Pictures = rent.Flat.Pictures;

            return View(model);
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RentFlat.Web/Controllers/RentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentFlat.Model;
using Microsoft.AspNet.Identity;
using Microsoft.VisualBasic;

namespace RentFlat.Web.Controllers
{
    [Authorize]
    public class RentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rents
        public async Task<ActionResult> Index()
        {
            string userId = User.Identity.GetUserId();
            var rents = db.Rents.Include(r => r.Flat).Where( id => id.Flat.OwnerId == userId);
            return View(await rents.ToListAsync());
        }

        // GET: Rents/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = await db.Rents.FindAsync(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            return View(rent);
        }

        // GET: Rents/Create
        public ActionResult Create()
        {
            string userId = User.Identity.GetUserId();
            var flats = db.Flats.Where(id => id.OwnerId == userId).ToList();
            ViewBag.FlatId = new SelectList(flats, "ID", "FlatName");
            return View();
        }

        // POST: Rents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Rent rent)
        {
            string userId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Rents.Add(rent);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            var flats = db.Flats.Where(id => id.OwnerId == userId).ToList();
            ViewBag.FlatId = new SelectList(db.Flats, "ID", "FlatName", rent.FlatId);
            return View(rent);
        }

        // GET: Rents/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = await db.Rents.FindAsync(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            ViewBag.FlatId = new SelectList(db.Flats, "ID", "FlatName", rent.FlatId);
            return View(rent);
        }

        // POST: Rents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,RentingUserId,FlatId,StartOfRent,EndOfRent")] Rent rent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rent).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.FlatId = new SelectList(db.Flats, "ID", "FlatName", rent.FlatId);
            return View(rent);
        }

        // GET: Rents/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = await db.Rents.FindAsync(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            return View(rent);
        }

        // POST: Rents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Rent rent = await db.Rents.FindAsync(id);
            db.Rents.Remove(rent);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async System.Threading.Tasks.Task<ActionResult> RentAFlat(int? id)
        {
            if (HttpContext.Request.Cookies["userEmail"] == null)
            {
                return View("NoSuchRules");
            }
            IEnumerable<Rent> rents = await db.Rents.ToListAsync();
            var currentRent = rents.Where(i => i.FlatId == id && i.StartOfRent < DateTime.Now && i.EndOfRent > DateTime.Now)
                .FirstOrDefault();
            if (currentRent != null)
            {
                return View("CantRent");
            }
            Flat flat = await db.Flats.FindAsync(id);
            return View(new Rent() { FlatId = flat.ID });
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> RentAFlat(Rent rent)
        {
            Flat flat = await db.Flats.FindAsync(rent.FlatId);
            DateInterval interval = DateInterval.Day;
            long difference = DateAndTime.DateDiff(interval, rent.StartOfRent.Value, rent.EndOfRent.Value, FirstDayOfWeek.Monday);
            decimal price = difference > 30 == true ? flat.PriceForMonth / 30 * difference : flat.PriceForDay * difference;
            ViewBag.Price = price;
            return View("Confirmation", rent);
        }

        [NonAction]
        private bool RentExists(int id)
        {
            return db.Rents.Count(e => e.ID == id) > 0;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RentFlat.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RentFlat.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RentFlat.Web/Views/Home/Index.cshtml
@model IEnumerable<RentFlat.Model.Rent>
@{
    ViewBag.Title = "Home Page";
    var keywords = ViewBag.keywords;
    var city = ViewBag.city;
}

<div class="row top-home-banner">
    <div class="container padding-top-30">
        <div class="row">
            <div class="col-xs-12 text-left padding-top-0 padding-left-0 padding-bottom-20">
                <strong class="text-white font-48 margin-top-10 font-lato font-weight-700" style="color: #ffffff;">
                    Find the best apartments
                </strong>
                <p class="text-white font-17 padding-top-15" style="color: #ffffff;">
                    Get apartments at your best location &nbsp;|&nbsp; aparment booking
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 padding-top-30 padding-bottom-30">
                @using (Html.BeginForm("Index", "Home", FormMethod.Get))
            {
                    <div class="col-md-6 col-sm-6 padding-0">
                        <div class="form-group text-left">
                            <input class="form-control" type="text" name="keywords" 
                                placeholder="Search By keywords i.e apartments, rooms, etc" value=@keywords >
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-4 padding-0">
                        <div class="form-group">
                            <input class="form-control" type="text" name="city" placeholder="Enter City or ZipCode" value=@city >
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-2 text-left">
                        <div class="form-group">
                            <input type="submit" value="Search" class="form-control btn btn-success">
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<div class="row">
    @if(Model != null && Model.Count() > 0)
    {
        <h5>Search Results: @Model.Count()</h5>

        <table class="table table-hover table-responsive">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Flat.FlatName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Flat.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Flat.City)
                </th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Flat.FlatName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Flat.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Flat.City)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Rents", "Home", new { id = item.ID }, null)
                    </td>
                </tr>
            }

        </table>
    }
</div>

RentFlat.Web/Views/Home/Rents.cshtml
@model RentFlat.Web.Models.ViewModels.RentViewModel
@{
    ViewBag.Title = "Rent Flat Details";
}
<div class="row">
    <h2>
        @ViewBag.Title
    </h2>
    <hr />
</div>
<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.RoomNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RoomNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Country)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Country)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.District)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.District)
            </dd>
            @if (Model.Facilities != null && Model.Facilities.Count() > 0)
            {
                <dt>
                    Facilities
                </dt>
                foreach (var i in Model.Facilities)
                {
                    <dd>
                        @Html.DisplayFor(model => i.Type)
                    </dd>
                }
            }

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PriceForDay)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PriceForDay)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PriceForMonth)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PriceForMonth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Latitude)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Latitude)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Longitude)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Longitude)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ZipCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ZipCode)
            </dd>
            @if (Model.Pictures != null && Model.Pictures.Count() > 0)
            {
                <dt>
                    Pictures
                </dt>
                foreach (var i in Model.Pictures)
                {
                    <dd>
                        @Html.DisplayFor(model => i.Name)
                    </dd>
                }
            }

        </dl>
    </div>
    <div class="col-md-6">
        <div id="map"></div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        //$(document).ready(function () {
        //    initMap();
        //});
        var map;
        function initMap() {
            var modelPoint = new google.maps.LatLng(@Model.Latitude, @Model.Longitude);

            map = new google.maps.Map(document.getElementById('map'), {
                center: modelPoint,
                zoom: 18
            });
            var coordInfoWindow = new google.maps.InfoWindow();
            coordInfoWindow.setContent(createInfoWindowContent(modelPoint, map.getZoom()));
            coordInfoWindow.setPosition(modelPoint);
            coordInfoWindow.open(map);

            map.addListener('zoom_changed', function() {
                coordInfoWindow.setContent(createInfoWindowContent(modelPoint, map.getZoom()));
                coordInfoWindow.open(map);
            });
        }
        var TILE_SIZE = 256;

        function createInfoWindowContent(latLng, zoom) {
            var scale = 1 << zoom;

            var worldCoordinate = project(latLng);

            var pixelCoordinate = new google.maps.Point(
                Math.floor(worldCoordinate.x * scale),
                Math.floor(worldCoordinate.y * scale));

            var tileCoordinate = new google.maps.Point(
                Math.floor(worldCoordinate.x * scale / TILE_SIZE),
                Math.floor(worldCoordinate.y * scale / TILE_SIZE));

            return [
                'Address: ' + '@Model.Address',
                'Day Price: ' + '@Model.PriceForDay',
                'Month Price: ' + '@Model.PriceForMonth'
            ].join('<br>');
        }

        function project(latLng) {
            var siny = Math.sin(latLng.lat() * Math.PI / 180);

            // Truncating to 0.9999 effectively limits latitude to 89.189. This is
            // about a third of a tile past the edge of the world tile.
            siny = Math.min(Math.max(siny, -0.9999), 0.9999);

            return new google.maps.Point(
                TILE_SIZE * (0.5 + latLng.lng() / 360),
                TILE_SIZE * (0.5 - Math.log((1 + siny) / (1 - siny)) / (4 * Math.PI)));
        }

    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyEA_0SheytW1x5JWIfkDXfRmadZlb1zs&callback=initMap">
    </script>
}